#!/bin/sh

#### Color scape codes ####
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color
###########################

# Get commit files
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Get the running container 
CURRENT_PROJECT=${PWD##*/}
CONTAINER=$(sudo docker ps --format "{{.Names}}" |  grep "$CURRENT_PROJECT")

if [ -z "$CONTAINER" ]; then
    echo "${YELLOW}WARNING: You need to start the container to auto format the code. Check if your code is OK.${NC}"
    # print the same message but with the project name in red
else
    echo "${BLUE}Formatting your code...${NC}"
    # Prettify all selected files
    sudo docker exec --workdir /devel $CONTAINER yarn prettier --ignore-unknown --write $FILES
    echo "${GREEN}Formatting done${NC}"
    # Add back the modified/prettified files to staging
    echo "${BLUE}Runing git add for formatted files${NC}"
    git add $FILES
    echo "${GREEN}Commit successfully created :)${NC}"
fi

exit 0