env:
  browser: true
  es2021: true
parser: "babel-eslint"
extends:
  - "plugin:react/recommended"
  - airbnb
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  camelcase: "off"
  import/no-cycle: "off"
  import/no-unresolved: "off"
  import/prefer-default-export: "off"
  jsx-a11y/label-has-associated-control: "off"
  jsx-a11y/no-static-element-interactions: "off"
  no-continue: "off"
  no-restricted-syntax: "off"
  no-underscore-dangle: "off"
  no-useless-escape: "off"
  no-warning-comments: [1, { "terms": ["FIXME", "TODO", "HACK"] }]
  react/forbid-prop-types: "off"
  react/jsx-filename-extension: [1, { "extensions": [".js"] }]
  react/jsx-props-no-spreading: "off"
