#!/bin/sh

# This script allows to execute yarn in the application that is currently running.

#### Color scape codes ####
RED='\033[0;31m'
NC='\033[0m' # No Color
###########################

CURRENT_PROJECT=${PWD##*/}
CONTAINER=$(docker ps --format "{{.Names}}" |  grep "$CURRENT_PROJECT")

if [ -z "$CONTAINER" ]; then
    echo -e "The container for the $RED'$CURRENT_PROJECT'$NC service does not exist or is not running"
    # print the same message but with the project name in red
else
    docker exec --workdir /devel -ti $CONTAINER yarn $*
fi
